# Generated by Django 4.2.30 on 2026-05-26 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOGIN', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
