# Generated by Django 4.2.30 on 2026-05-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOGIN', '0002_alter_newuser_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='last_login_act',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
