# Generated by Django 4.2.30 on 2026-05-19 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BLOG', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organiztion',
            name='founder',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationfollowing',
            name='following',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BLOG.organiztion'),
        ),
        migrations.AddField(
            model_name='organizationfollowing',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_following', to='BLOG.organiztion'),
        ),
        migrations.AddField(
            model_name='organizationfollower',
            name='follower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BLOG.organiztion'),
        ),
        migrations.AddField(
            model_name='organizationfollower',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_follower', to='BLOG.organiztion'),
        ),
        migrations.AddField(
            model_name='followunnotification',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='followunnotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_follow_notification', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blogread',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_read', to='BLOG.blog'),
        ),
        migrations.AddField(
            model_name='blogread',
            name='read_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blognotification',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_notification', to='BLOG.blog'),
        ),
        migrations.AddField(
            model_name='blognotification',
            name='sent_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bloglike',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_like', to='BLOG.blog'),
        ),
        migrations.AddField(
            model_name='bloglike',
            name='like_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blog',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blog',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BLOG.organiztion'),
        ),
        migrations.AddField(
            model_name='blog',
            name='tag',
            field=models.ManyToManyField(to='BLOG.tag'),
        ),
        migrations.AddConstraint(
            model_name='organizationfollowing',
            constraint=models.CheckConstraint(check=models.Q(('organization', models.F('following')), _negated=True), name='organization_cannot_follow_itself'),
        ),
        migrations.AlterUniqueTogether(
            name='organizationfollowing',
            unique_together={('organization', 'following')},
        ),
        migrations.AddConstraint(
            model_name='organizationfollower',
            constraint=models.CheckConstraint(check=models.Q(('organization', models.F('follower')), _negated=True), name='organization_cannot_become_follower_of_itself'),
        ),
        migrations.AlterUniqueTogether(
            name='organizationfollower',
            unique_together={('organization', 'follower')},
        ),
        migrations.AlterUniqueTogether(
            name='blogread',
            unique_together={('blog', 'read_by')},
        ),
        migrations.AlterUniqueTogether(
            name='blognotification',
            unique_together={('blog', 'sent_to')},
        ),
        migrations.AlterUniqueTogether(
            name='bloglike',
            unique_together={('blog', 'like_user')},
        ),
    ]
