# Generated by Django 4.2.30 on 2026-05-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG', '0004_streak'),
    ]

    operations = [
        migrations.AddField(
            model_name='streak',
            name='max_streak',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='streak',
            name='count',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
