# Generated by Django 4.2.30 on 2026-05-26 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG', '0005_streak_max_streak_alter_streak_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='pin',
        ),
        migrations.CreateModel(
            name='PinBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pinnedblog', to='BLOG.blog')),
            ],
        ),
    ]
